module.exports = {
  caseType:'operator_approved_port_call_plan', initialState:'port_call_received',
  states:['port_call_received','sources_synchronized','constraints_review','plan_proposed','operator_approved','dispatched','executing','exception_recovery','completed'],
  createRoles:['port_planner','operations_manager'],
  assessmentRoles:['port_planner','harbor_operator','safety_officer','environmental_reviewer'],
  auditRoles:['operations_manager','safety_officer','environmental_reviewer'],
  connectorRoles:['integration_operator','operations_manager'],
  evidenceKinds:['vessel_snapshot','berth_snapshot','cargo_manifest_digest','customs_status','weather_tide_snapshot','environmental_rule_version','labor_equipment_snapshot','plan_manifest','operator_approval','dispatch_receipt','exception_record','realized_outcome'],
  requiredSignals:['sourceTimestamp','evaluatedAt','staleAfterSeconds','vesselVersion','berthVersion','weatherVersion','customsStatus','environmentalRuleVersion','safetyLimitsVerified','policyVersion'],
  professionalBoundary:'Plans are advisory; this service cannot clear customs, navigate vessels, allocate regulated resources, or issue port-control commands.',
  connectors:[
    {name:'ais_port_community',purpose:'vessel and port-call snapshots'},
    {name:'terminal_operating_system',purpose:'berth/cargo status'},
    {name:'customs',purpose:'clearance receipts'},
    {name:'weather_tides',purpose:'effective-time conditions'},
    {name:'erp_wms_tms',purpose:'cargo and resource state'},
    {name:'maintenance',purpose:'equipment availability'},
    {name:'environmental_rules',purpose:'authoritative rule-version references'},
    {name:'notification',purpose:'operator and exception receipts'},
  ],
  transitions:[
    {from:'port_call_received',action:'synchronize_sources',to:'sources_synchronized',roles:['integration_operator','port_planner'],requiresEvidence:true},
    {from:'sources_synchronized',action:'review_constraints',to:'constraints_review',roles:['port_planner','safety_officer','environmental_reviewer'],requiresEvidence:true},
    {from:'constraints_review',action:'propose_plan',to:'plan_proposed',roles:['port_planner'],requiresEvidence:true},
    {from:'plan_proposed',action:'approve',to:'operator_approved',roles:['harbor_operator','operations_manager'],requiresEvidence:true,dualControl:true},
    {from:'operator_approved',action:'record_dispatch',to:'dispatched',roles:['harbor_operator'],requiresEvidence:true},
    {from:'dispatched',action:'start_execution',to:'executing',roles:['harbor_operator'],requiresEvidence:true},
    {from:'executing',action:'open_exception',to:'exception_recovery',roles:['harbor_operator','safety_officer'],requiresEvidence:true},
    {from:'executing',action:'complete',to:'completed',roles:['harbor_operator'],requiresEvidence:true,dualControl:true},
    {from:'exception_recovery',action:'complete',to:'completed',roles:['operations_manager'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const source=Date.parse(x.sourceTimestamp);const evaluated=Date.parse(x.evaluatedAt);const limit=Number(x.staleAfterSeconds);const stale=!Number.isFinite(source)||!Number.isFinite(evaluated)||!Number.isFinite(limit)||limit<=0||evaluated<source||(evaluated-source)/1000>limit;return{disposition:stale||x.customsStatus!=='cleared'||x.safetyLimitsVerified!==true?'operational_hold_manual_fallback':'harbor_operator_review_required',dispatchCommand:null,stale,versions:{vessel:x.vesselVersion,berth:x.berthVersion,weather:x.weatherVersion,environmental:x.environmentalRuleVersion}};},
};
